# -*- coding: utf-8 -*-
"""3D Mesh from an Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DodkqqN1M0F_EXZw1vqlUN7gHq5iqS_M
"""

!pip install -q transformers pillow matplotlib

import matplotlib.pyplot as plt
from PIL import Image
import torch
from transformers import GLPNImageProcessor, GLPNForDepthEstimation
from google.colab import files

uploaded = files.upload()

image_path = next(iter(uploaded.keys()))

feature_extractor = GLPNImageProcessor.from_pretrained("vinvino02/glpn-nyu")
model = GLPNForDepthEstimation.from_pretrained("vinvino02/glpn-nyu")

image = Image.open(image_path).convert("RGB")

new_height = 480 if image.height > 480 else image.height
new_height -= (new_height % 32)

new_width = int(new_height * image.width / image.height)
diff = new_width % 32
new_width = new_width - diff if diff < 16 else new_width + 32 - diff

new_size = (new_width, new_height)
image = image.resize(new_size)

inputs = feature_extractor(images=image, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)
    predicted_depth = outputs.predicted_depth

pad = 16
output = predicted_depth.squeeze().cpu().numpy() * 1000.0
output = output[pad:-pad, pad:-pad]
cropped_image = image.crop((pad, pad, image.width - pad, image.height - pad))

fig, ax = plt.subplots(1, 2, figsize=(12, 6))

ax[0].imshow(cropped_image)
ax[0].set_title("Input Image")
ax[0].axis("off")

ax[1].imshow(output, cmap="plasma")
ax[1].set_title("Predicted Depth")
ax[1].axis("off")

plt.tight_layout()
plt.show()

"""# Yay! got the predicted depth from single monocular image"""

!pip install -q open3d

import numpy as np
import open3d as o3d

color_np = np.array(cropped_image)

depth_np = output.astype(np.float32)

depth_o3d = o3d.geometry.Image(depth_np)
color_o3d = o3d.geometry.Image(color_np)

rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
    color_o3d,
    depth_o3d,
    convert_rgb_to_intensity=False
)

h, w = depth_np.shape
fx = fy = 500
cx = w / 2
cy = h / 2

camera_intrinsic = o3d.camera.PinholeCameraIntrinsic(
    width=w,
    height=h,
    fx=fx,
    fy=fy,
    cx=cx,
    cy=cy
)

pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
    rgbd_image,
    camera_intrinsic
)

pcd.transform([[1, 0, 0, 0],
               [0, -1, 0, 0],
               [0, 0, -1, 0],
               [0, 0, 0, 1]])

o3d.io.write_point_cloud("output.ply", pcd)

print("Saved point cloud as output.ply")

o3d.visualization.draw_plotly([pcd])

"""# Got the point cloud"""

import open3d as o3d
import numpy as np

cl, ind = pcd.remove_statistical_outlier(nb_neighbors=20, std_ratio=2.0)
pcd = pcd.select_by_index(ind)

# --- Normals ---
pcd.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.05, max_nn=30)
)

pcd.orient_normals_to_align_with_direction(np.array([0.0, 0.0, 1.0]))

mesh, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(
    pcd, depth=9
)

densities = np.asarray(densities)
vertices_to_remove = densities < np.quantile(densities, 0.05)
mesh.remove_vertices_by_mask(vertices_to_remove)

R = mesh.get_rotation_matrix_from_xyz((np.pi, 0, 0))
mesh.rotate(R, center=(0, 0, 0))

o3d.io.write_triangle_mesh("mesh.obj", mesh)
print("Mesh saved as mesh.obj")

o3d.visualization.draw_plotly([mesh])